name: Backport Pull Request

on:
  push:
    branches:
      - main

jobs:
  backport:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find merged pull requests
        id: find_prs
        run: |
          PULL_REQUESTS=$(git log --pretty='%s' main..develop | grep -E 'Merge pull request #[0-9]+' | sed -E 's/.*#([0-9]+).*/\1/' | sort -n | uniq)
          echo "PR_LIST=$PULL_REQUESTS" >> $GITHUB_ENV

      - name: Backport pull requests
        run: |
          PR_LIST=${{ env.PR_LIST }}
          IFS=' ' read -ra PR_ARRAY <<< "$PR_LIST"

          for PR in "${PR_ARRAY[@]}"; do
            NEW_BRANCH="backport/PR-${PR}"
            git checkout -b $NEW_BRANCH main
            git cherry-pick $PR
            git push origin $NEW_BRANCH
          done